# @package _global_
config:
  MODEL:
    TRUNK:
      NAME: resnet
      TRUNK_PARAMS:
        RESNETS:
          DEPTH: 50
          WIDTH_MULTIPLIER: 3
    HEAD:
      PARAMS: [['mlp', {'dims': [6144, 205]}]]
