# @package _global_
config:
  DATA:
    TRAIN:
      TRANSFORMS:
        - name: Resize
          size: [256, 256]
        - name: CenterCrop
          size: 227
        - name: RandomHorizontalFlip
        - name: ImgPilToRawTensor
        - name: Normalize
          mean: [123.675, 116.28, 103.53]
          std: [1.0, 1.0, 1.0]
    TEST:
        TRANSFORMS:
          - name: Resize
            size: [256, 256]
          - name: CenterCrop
            size: 227
          - name: ImgPilToRawTensor
          - name: Normalize
            mean: [123.675, 116.28, 103.53]
            std: [1.0, 1.0, 1.0]
  MODEL:
    FEATURE_EVAL_SETTINGS:
      LINEAR_EVAL_FEAT_POOL_OPS_MAP: [
          ["conv1", ["AvgPool2d", [[19, 19], 4, 0]]],
          ["conv2", ["AvgPool2d", [[12, 12], 3, 0]]],
          ["conv3", ["AvgPool2d", [[9, 9], 1, 0]]],
          ["conv4", ["AvgPool2d", [[9, 9], 1, 0]]],
          ["conv5", ["AvgPool2d", [[8, 8], 1, 0]]],
      ]
    TRUNK:
      NAME: alexnet_bvlc
    HEAD:
      PARAMS: [["mlp", {"dims": [9216, 20]}]]
