# @package _global_
config:
  MODEL:
    FEATURE_EVAL_SETTINGS:
      LINEAR_EVAL_FEAT_POOL_OPS_MAP: [
        ["res4", ["AdaptiveAvgPool2d", [[5, 1]]]],
        ["res5", ["AdaptiveAvgPool2d", [[2, 1]]]],
        ["avgpool", ["Identity", []]],
      ]
    TRUNK:
      NAME: regnet
      TRUNK_PARAMS:
        REGNET:
          depth: 20
          w_0: 352
          w_a: 147.48
          w_m: 2.4
          group_width: 328
    HEAD:
      PARAMS: [["mlp", {"dims": [2048, 20]}]]
