# @package _global_
config:
  VERBOSE: True
  LOG_FREQUENCY: 100
  TEST_ONLY: False
  TEST_EVERY_NUM_EPOCH: 1
  TEST_MODEL: True
  SEED_VALUE: 0
  MULTI_PROCESSING_METHOD: forkserver
  DATA:
    NUM_DATALOADER_WORKERS: 5
    TRAIN:
      DATA_SOURCES: [everstore]
      LABEL_SOURCES: [disk_filelist]
      DATASET_NAMES: [inaturalist2018_everstore]
      BATCHSIZE_PER_REPLICA: 32
      TRANSFORMS:
        - name: Resize
          size: 256
        - name: RandomCrop
          size: 224
        - name: RandomHorizontalFlip
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: False
      COPY_DESTINATION_DIR: /tmp/inaturalist2018/
    TEST:
      DATA_SOURCES: [everstore]
      LABEL_SOURCES: [disk_filelist]
      DATASET_NAMES: [inaturalist2018_everstore]
      BATCHSIZE_PER_REPLICA: 32
      TRANSFORMS:
        - name: Resize
          size: 256
        - name: CenterCrop
          size: 224
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: False
      COPY_DESTINATION_DIR: /tmp/inaturalist2018/
  METERS:
    name: accuracy_list_meter
    accuracy_list_meter:
      num_meters: 5
      topk_values: [1, 5]
  TRAINER:
    TRAIN_STEP_NAME: standard_train_step
  MODEL:
    FEATURE_EVAL_SETTINGS:
      EVAL_MODE_ON: True
      FREEZE_TRUNK_ONLY: True
      SHOULD_FLATTEN_FEATS: False
      LINEAR_EVAL_FEAT_POOL_OPS_MAP: [
          ["conv1", ["AvgPool2d", [[19, 19], 4, 0]]],
          ["conv2",["AvgPool2d", [[12, 12], 3, 0]]],
          ["conv3",["AvgPool2d", [[9, 9], 1, 0]]],
          ["conv4",["AvgPool2d", [[9, 9], 1, 0]]],
          ["conv5",["AvgPool2d", [[8, 8], 1, 0]]],
      ]
    TRUNK:
      NAME: alexnet_deepcluster
    HEAD:
      PARAMS: [
        ["eval_mlp", {"in_channels": 96, "dims": [9600, 8142]}],
        ["eval_mlp", {"in_channels": 256, "dims": [9216, 8142]}],
        ["eval_mlp", {"in_channels": 384, "dims": [9600, 8142]}],
        ["eval_mlp", {"in_channels": 384, "dims": [9600, 8142]}],
        ["eval_mlp", {"in_channels": 256, "dims": [9216, 8142]}],
      ]
      BATCHNORM_MOMENTUM: 0.1
    WEIGHTS_INIT:
      PARAMS_FILE: "specify the model weights"
      STATE_DICT_KEY_NAME: model_state_dict
  LOSS:
    name: cross_entropy_multiple_output_single_target
    cross_entropy_multiple_output_single_target:
      ignore_index: -1
  OPTIMIZER:
      name: sgd
      weight_decay: 0.0005
      momentum: 0.9
      num_epochs: 84
      nesterov: False
      regularize_bn: False
      regularize_bias: True
      param_schedulers:
        lr:
          auto_lr_scaling:
            auto_scale: true
            base_value: 0.01
            base_lr_batch_size: 256
          name: multistep
          values: [0.01, 0.001, 0.0001, 0.00001]
          milestones: [24, 48, 72]
          update_interval: epoch
  DISTRIBUTED:
    BACKEND: nccl
    NUM_NODES: 1
    NUM_PROC_PER_NODE: 8
    INIT_METHOD: tcp
    RUN_ID: auto
  MACHINE:
    DEVICE: gpu
  CHECKPOINT:
    DIR: "."
    AUTO_RESUME: True
    CHECKPOINT_FREQUENCY: 1
