# @package _global_
config:
  DATA:
    TRAIN:
      DATA_SOURCES: [disk_filelist]
      LABEL_SOURCES: [disk_filelist]
      DATASET_NAMES: [imagenet1k_folder]
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: True
      COPY_DESTINATION_DIR: /tmp/imagenet1k/
    TEST:
      DATA_SOURCES: [disk_filelist]
      LABEL_SOURCES: [disk_filelist]
      DATASET_NAMES: [imagenet1k_folder]
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: True
      COPY_DESTINATION_DIR: /tmp/imagenet1k/
  MACHINE:
    NUM_DATALOADER_WORKERS: 4
