# @package _global_
config:
  MODEL:
    TRUNK:
      NAME: resnet
      TRUNK_PARAMS:
        RESNETS:
          DEPTH: 50
          WIDTH_MULTIPLIER: 2
    HEAD:
      PARAMS: [["mlp", {"dims": [4096, 128]}]]
