# @package _global_
config:
  DATA:
    NUM_DATALOADER_WORKERS: 8
    TRAIN:
      BATCHSIZE_PER_REPLICA: 32
      TRANSFORMS:
        - name: Resize
          size: 256
          interpolation: 3
        - name: CenterCrop
          size: 224
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
    TEST:
      BATCHSIZE_PER_REPLICA: 32
      TRANSFORMS:
        - name: Resize
          size: 256
          interpolation: 3
        - name: CenterCrop
          size: 224
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
  METERS:
    name: accuracy_list_meter
    accuracy_list_meter:
      num_meters: 5
      topk_values: [1, 5]
  MODEL:
    FEATURE_EVAL_SETTINGS:
      EVAL_MODE_ON: True
      FREEZE_TRUNK_ONLY: True
      EXTRACT_TRUNK_FEATURES_ONLY: True
      SHOULD_FLATTEN_FEATS: False
      LINEAR_EVAL_FEAT_POOL_OPS_MAP: [
        ["lastCLS", ["Identity", []] ],
      ]
    TRUNK: # S-16
      NAME: vision_transformer
      VISION_TRANSFORMERS:
        IMAGE_SIZE: 224
        PATCH_SIZE: 16
        HIDDEN_DIM: 384
        NUM_LAYERS: 12
        NUM_HEADS: 6
        MLP_DIM: 1536
        CLASSIFIER: token
        DROPOUT_RATE: 0
        ATTENTION_DROPOUT_RATE: 0
        QKV_BIAS: True
        DROP_PATH_RATE: 0.1 # stochastic depth dropout probability
    HEAD:
      PARAMS: []
    SYNC_BN_CONFIG:
      CONVERT_BN_TO_SYNC_BN: True
      SYNC_BN_TYPE: pytorch
    WEIGHTS_INIT:
      # Use the teacher to perform the evaluation
      STATE_DICT_KEY_NAME: "loss"
      REMOVE_PREFIX: "momentum_teacher.module."
