# @package _global_
config:
  METERS:
    accuracy_list_meter:
      num_meters: 5
      topk_values: [1, 5]
  MODEL:
    FEATURE_EVAL_SETTINGS:
      LINEAR_EVAL_FEAT_POOL_OPS_MAP: [
        ["res5", ["AdaptiveAvgPool2d", [[3, 1]]]],
        ["res5", ["AdaptiveAvgPool2d", [[2, 2]]]],
        ["res5", ["AvgPool2d", [[5, 5], 2, 0]]],
        ["res5", ["AvgPool2d", [[4, 4], 3, 0]]],
        ["res5", ["AvgPool2d", [[6, 6], 1, 0]]],
      ]
    TRUNK:
      NAME: regnet
      TRUNK_PARAMS:
        REGNET:
          name: regnet_y_16gf
    HEAD:
      PARAMS: [
        ["eval_mlp", {"in_channels": 3024, "dims": [9072, 1000]}],
        ["eval_mlp", {"in_channels": 3024, "dims": [12096, 1000]}],
        ["eval_mlp", {"in_channels": 3024, "dims": [12096, 1000]}],
        ["eval_mlp", {"in_channels": 3024, "dims": [12096, 1000]}],
        ["eval_mlp", {"in_channels": 3024, "dims": [12096, 1000]}],
      ]
