# @package _global_
config:
  METERS:
    name: accuracy_list_meter
    accuracy_list_meter:
      num_meters: 5
      topk_values: [1, 5]
  MODEL:
    FEATURE_EVAL_SETTINGS:
      LINEAR_EVAL_FEAT_POOL_OPS_MAP: [
        ["res4", ["AdaptiveAvgPool2d", [[3, 1]]]],
        # ["res4", ["AdaptiveAvgPool2d", [[1, 3]]]],
        # ["res4", ["AdaptiveAvgPool2d", [[4, 1]]]],
        # ["res4", ["AdaptiveAvgPool2d", [[1, 4]]]],
        ["res5", ["AdaptiveAvgPool2d", [[2, 1]]]],
        # ["res5", ["AdaptiveAvgPool2d", [[1, 2]]]],
        ["avgpool", ["Identity", []]],
        ["avgpool", ["Identity", []]],
      ]
    TRUNK:
      NAME: regnet
      TRUNK_PARAMS:
        REGNET:
          name: regnet_y_128gf
    HEAD:
      PARAMS: [
        ["eval_mlp", {"in_channels": 2904, "dims": [8712, 1000]}],
        # ["eval_mlp", {"in_channels": 2904, "dims": [8712, 1000]}],
        # ["eval_mlp", {"in_channels": 2904, "dims": [11616, 1000]}],
        # ["eval_mlp", {"in_channels": 2904, "dims": [11616, 1000]}],
        ["eval_mlp", {"in_channels": 7392, "dims": [14784, 1000]}],
        # ["eval_mlp", {"in_channels": 7392, "dims": [14784, 1000]}],
        ["eval_mlp", {"in_channels": 7392, "dims": [7392, 1000]}],
        ["mlp", {"dims": [7392, 1000]}],
      ]
