# @package _global_
config:
  DATA:
    TRAIN:
      DATASET_NAMES: ["imagenet1k-per20-random"]
  OPTIMIZER:
    param_schedulers:
      lr:
        auto_lr_scaling:
          auto_scale: true
          base_value: 0.01
          base_lr_batch_size: 256
        values: [0.01, 0.001]
