# @package _global_
config:
  MODEL:
    TRUNK: # S-16
      NAME: vision_transformer
      VISION_TRANSFORMERS:
        IMAGE_SIZE: 224
        PATCH_SIZE: 16
        HIDDEN_DIM: 384
        NUM_LAYERS: 12
        NUM_HEADS: 6
        MLP_DIM: 1536
        CLASSIFIER: token
        DROPOUT_RATE: 0.0
        ATTENTION_DROPOUT_RATE: 0
        QKV_BIAS: True
        DROP_PATH_RATE: 0.0
