# @package _global_
config:
  VERBOSE: True
  LOG_FREQUENCY: 100
  TEST_ONLY: False
  TEST_EVERY_NUM_EPOCH: 1
  TEST_MODEL: True
  SEED_VALUE: 0
  MULTI_PROCESSING_METHOD: forkserver
  MONITOR_PERF_STATS: True
  DATA:
    TRAIN:
      DATA_SOURCES: [everstore]
      LABEL_SOURCES: [disk]
      DATASET_NAMES: [places205-everstore]
      BATCHSIZE_PER_REPLICA: 32
      TRANSFORMS:
        - name: RandomResizedCrop
          size: 224
        - name: RandomHorizontalFlip
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: True
      COPY_DESTINATION_DIR: /tmp/places205_everstore/
    TEST:
      DATA_SOURCES: [everstore]
      LABEL_SOURCES: [disk]
      DATASET_NAMES: [places205-everstore]
      BATCHSIZE_PER_REPLICA: 32
      TRANSFORMS:
        - name: Resize
          size: 256
        - name: CenterCrop
          size: 224
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: True
      COPY_DESTINATION_DIR: /tmp/places205_everstore/
  METERS:
    accuracy_list:
      num_list: 5
      topk: [1, 5]
  TRAINER:
    TRAIN_STEP_NAME: standard
  MODEL:
    FEATURE_EVAL_MODE: True
    EVAL_FEATURES: ["conv1", "res2", "res3", "res4", "res5"]
    TRUNK:
      NAME: resnet
      TRUNK_PARAMS:
        RESNETS:
          DEPTH: 50
      LINEAR_FEAT_POOL_OPS: [
          ["AvgPool2d", [[10, 10], 10, 4]],
          ["AvgPool2d", [[16, 16], 8, 0]],
          ["AvgPool2d", [[13, 13], 5, 0]],
          ["AvgPool2d", [[8, 8], 3, 0]],
          ["AvgPool2d", [[6, 6], 1, 0]],
      ]
    HEAD:
      PARAMS: [
        ["eval_mlp", {"in_channels": 64, "dims": [9216, 205]}],
        ["eval_mlp", {"in_channels": 256, "dims": [9216, 205]}],
        ["eval_mlp", {"in_channels": 512, "dims": [8192, 205]}],
        ["eval_mlp", {"in_channels": 1024, "dims": [9216, 205]}],
        ["eval_mlp", {"in_channels": 2048, "dims": [8192, 205]}],
      ]
    PARAMS_FILE:
      PATH: "specify the weights here"
      STATE_DICT_KEY_NAME: classy_state_dict
      # STATE_DICT_KEY_NAME: model_state_dict
    SYNC_BN_CONFIG:
      CONVERT_BN_TO_SYNC_BN: True
      SYNC_BN_TYPE: apex
      GROUP_SIZE: 8
  CRITERION:
      name: cross_entropy_multiple_output_single_target
      ignore_index: -1
  OPTIMIZER:
      name: sgd
      # In the OSS Caffe2 benchmark, RN50 models use 1e-4 and AlexNet models 5e-4
      weight_decay: 0.0005
      momentum: 0.9
      num_epochs: 14
      nesterov: True
      regularize_bn: False
      regularize_bias: True
      param_schedulers:
        lr:
          base_value: 0.01
          name: multistep
          values: [0.01, 0.001, 0.0001, 0.00001]
          milestones: [4, 8, 12]
          update_interval: epoch
  DISTRIBUTED:
    BACKEND: nccl
    NUM_NODES: 1
    NUM_PROC_PER_NODE: 8
    INIT_METHOD: tcp
    RUN_ID: auto
  MACHINE:
    NUM_DATALOADER_WORKERS: 8
    DEVICE: gpu
  CHECKPOINT:
    DIR: "."
    AUTO_RESUME: True
    CHECKPOINT_FREQUENCY: 1
