# @package _global_
config:
  MODEL:
    TRUNK:
      NAME: alexnet_deepcluster
      LINEAR_FEAT_POOL_OPS: [
          ["AvgPool2d", [[19, 19], 4, 0]],
          ["AvgPool2d", [[12, 12], 3, 0]],
          ["AvgPool2d", [[9, 9], 1, 0]],
          ["AvgPool2d", [[9, 9], 1, 0]],
          ["AvgPool2d", [[8, 8], 1, 0]],
      ]
    HEAD:
      PARAMS: [
        ["eval_mlp", {"in_channels": 96, "dims": [9600, 8142]}],
        ["eval_mlp", {"in_channels": 256, "dims": [9216, 8142]}],
        ["eval_mlp", {"in_channels": 384, "dims": [9600, 8142]}],
        ["eval_mlp", {"in_channels": 384, "dims": [9600, 8142]}],
        ["eval_mlp", {"in_channels": 256, "dims": [9216, 8142]}],
      ]
