# @package _global_
config:
  MODEL:
    FEATURE_EVAL_SETTINGS:
      LINEAR_EVAL_FEAT_POOL_OPS_MAP: [
        ["res4", ["AdaptiveAvgPool2d", [[5, 1]]]],
        # ["res4", ["AdaptiveAvgPool2d", [[1, 5]]]],
        ["res5", ["AdaptiveAvgPool2d", [[2, 1]]]],
        # ["res5", ["AdaptiveAvgPool2d", [[1, 2]]]],
        # ["res5", ["AdaptiveAvgPool2d", [[3, 1]]]],
        # ["res5", ["AdaptiveAvgPool2d", [[1, 3]]]],
        ["avgpool", ["Identity", []]],
        # ["avgpool", ["Identity", []]],
      ]
    TRUNK:
      NAME: regnet
      TRUNK_PARAMS:
        REGNET:
          depth: 20
          w_0: 352
          w_a: 147.48
          w_m: 2.4
          group_width: 328
    HEAD:
      PARAMS: [
        ["eval_mlp", {"in_channels": 1968, "dims": [9840, 205]}],
        # ["eval_mlp", {"in_channels": 1968, "dims": [9840, 205]}],
        ["eval_mlp", {"in_channels": 4920, "dims": [9840, 205]}],
        # ["eval_mlp", {"in_channels": 4920, "dims": [9840, 205]}],
        # ["eval_mlp", {"in_channels": 4920, "dims": [14760, 205]}],
        # ["eval_mlp", {"in_channels": 4920, "dims": [14760, 205]}],
        ["eval_mlp", {"in_channels": 4920, "dims": [4920, 205]}],
        # ["mlp", {"dims": [4920, 205]}],
      ]
