# @package _global_
config:
  VERBOSE: False
  LOG_FREQUENCY: 100
  TEST_ONLY: False
  TEST_EVERY_NUM_EPOCH: 5
  TEST_MODEL: True
  SEED_VALUE: 1
  MULTI_PROCESSING_METHOD: forkserver
  MONITOR_PERF_STATS: False
  DATA:
    TRAIN:
      DATA_SOURCES: [disk]
      DATASET_NAMES: [imagenet1k]
      BATCHSIZE_PER_REPLICA: 32
      TRANSFORMS:
        - name: ImgRotatePil
        - name: RandomResizedCrop
          size: 224
        - name: RandomHorizontalFlip
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: True
      COPY_DESTINATION_DIR: /tmp/imagenet1k/
    TEST:
      DATA_SOURCES: [disk]
      DATASET_NAMES: [imagenet1k]
      BATCHSIZE_PER_REPLICA: 32
      TRANSFORMS:
        - name: ImgRotatePil
        - name: Resize
          size: 256
        - name: CenterCrop
          size: 224
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: True
      COPY_DESTINATION_DIR: /tmp/imagenet1k/
  METERS:
    accuracy_list:
      num_list: 1
      topk: [1]
  TRAINER:
    TRAIN_STEP_NAME: standard
  MODEL:
    TRUNK:
      NAME: resnet
      TRUNK_PARAMS:
        RESNETS:
          DEPTH: 50
    HEAD:
      PARAMS: [["mlp", {"dims": [2048, 4]}]]
  CRITERION:
      name: cross_entropy_multiple_output_single_target
      ignore_index: -1
  OPTIMIZER:
      name: sgd
      weight_decay: 0.0001
      momentum: 0.9
      num_epochs: 90
      nesterov: False
      regularize_bn: False
      regularize_bias: True
      param_schedulers:
        lr:
          base_value: 0.1
          name: multistep
          values: [0.1, 0.01, 0.001]
          milestones: [30, 60]
          update_interval: epoch
  DISTRIBUTED:
    BACKEND: nccl
    NUM_NODES: 1
    NUM_PROC_PER_NODE: 8
    INIT_METHOD: tcp
    RUN_ID: auto
  MACHINE:
    NUM_DATALOADER_WORKERS: 5
    DEVICE: gpu
  CHECKPOINT:
    DIR: "."
    AUTO_RESUME: True
    CHECKPOINT_FREQUENCY: 1
