# @package _global_
config:
  DATA:
    NUM_DATALOADER_WORKERS: 4
    TRAIN:
      DATA_SOURCES: [torchvision_dataset]
      LABEL_SOURCES: [torchvision_dataset]
      DATASET_NAMES: [STL10]
      TRANSFORMS:
        - name: RandomResizedCrop
          size: 32
        - name: RandomHorizontalFlip
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: False
      COPY_DESTINATION_DIR: /tmp/stl10/
    TEST:
      DATA_SOURCES: [torchvision_dataset]
      LABEL_SOURCES: [torchvision_dataset]
      DATASET_NAMES: [STL10]
      TRANSFORMS:
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: False
      COPY_DESTINATION_DIR: /tmp/stl10/
  METERS:
    name: accuracy_list_meter
    accuracy_list_meter:
      num_meters: 1
      topk_values: [1]
  MODEL:
    FEATURE_EVAL_SETTINGS:
      LINEAR_EVAL_FEAT_POOL_OPS_MAP: [
        ["res5", ["AdaptiveAvgPool2d", [[1, 1]]]],
      ]
    HEAD:
      PARAMS: [
        ["eval_mlp", {"in_channels": 2048, "dims": [2048, 10]}],
      ]
