# @package _global_
config:
  DATA:
    TRAIN:
      BATCHSIZE_PER_REPLICA: 32
      TRANSFORMS:
        - name: ImgPilToMultiCrop
          total_num_crops: 6
          size_crops: [224, 96]
          num_crops: [2, 4]
          crop_scales: [[0.14, 1], [0.05, 0.14]]
        - name: RandomHorizontalFlip
          p: 0.5
        - name: ImgPilColorDistortion
          strength: 1.0
        - name: ImgPilGaussianBlur
          p: 0.5
          radius_min: 0.1
          radius_max: 2.0
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
  MODEL:
    TRUNK:
      NAME: resnet
      TRUNK_PARAMS:
        RESNETS:
          DEPTH: 50
          WIDTH_MULTIPLIER: 2
    HEAD:
      PARAMS: [
        ["swav_head", {"dims": [4096, 8192, 128], "use_bn": True, "num_clusters": [3000]}],
      ]
  DISTRIBUTED:
    NUM_NODES: 16
    NUM_PROC_PER_NODE: 8
