# @package _global_
config:
  VERBOSE: False
  LOG_FREQUENCY: 10
  TEST_ONLY: False
  TEST_MODEL: False
  SEED_VALUE: 0
  MULTI_PROCESSING_METHOD: forkserver
  MONITOR_PERF_STATS: True
  ROLLING_BTIME_FREQ: 313
  TENSORBOARD_SETUP:
      USE_TENSORBOARD: True
      EXPERIMENT_LOG_DIR: "moco_v2_reference"
      LOG_PARAMS: False
      FLUSH_EVERY_N_MIN: 20
  DATA:
    NUM_DATALOADER_WORKERS: 5
    TRAIN:
      DATA_SOURCES: [disk_folder]
      DATASET_NAMES: [imagenet1k_folder]
      BATCHSIZE_PER_REPLICA: 32
      LABEL_TYPE: sample_index    # just an implementation detail. Label isn't used
      TRANSFORMS:
        - name: ImgReplicatePil
          num_times: 2
        - name: RandomResizedCrop
          size: 224
        - name: ImgPilColorDistortion
          strength: 0.5
        - name: ImgPilGaussianBlur
          p: 0.5
          radius_min: 0.1
          radius_max: 2.0
        - name: RandomHorizontalFlip
          p: 0.5
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      COLLATE_FUNCTION: moco_collator
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: False
      COPY_DESTINATION_DIR: /tmp/imagenet1k/
      DROP_LAST: True
  TRAINER:
    TRAIN_STEP_NAME: standard_train_step
  METERS:
    name: ""
  MODEL:
    TRUNK:
      NAME: resnet
      TRUNK_PARAMS:
        RESNETS:
          DEPTH: 50
          ZERO_INIT_RESIDUAL: True
    HEAD:
      PARAMS: [
        ["mlp", {"dims": [2048, 2048], "use_relu": True}],
        ["mlp", {"dims": [2048, 128]}],
      ]
    SYNC_BN_CONFIG:
      CONVERT_BN_TO_SYNC_BN: False
    AMP_PARAMS:
      USE_AMP: False
  LOSS:
      name: moco_loss
      moco_loss:
        embedding_dim: 128
        queue_size: 65536
        momentum: 0.999
        temperature: 0.2
  OPTIMIZER:
      name: sgd
      use_larc: False
      weight_decay: 0.0001
      momentum: 0.9
      nesterov: True
      num_epochs: 200
      regularize_bn: True
      regularize_bias: True
      param_schedulers:
        lr:
          name: multistep
          values: [0.03, 0.003, 0.0003]
          milestones: [120, 160]
          update_interval: epoch
  DISTRIBUTED:
    BACKEND: nccl
    NUM_NODES: 1
    NUM_PROC_PER_NODE: 8
    INIT_METHOD: tcp
    RUN_ID: auto
  MACHINE:
    DEVICE: gpu
  CHECKPOINT:
    AUTO_RESUME: True
    CHECKPOINT_FREQUENCY: 5
    CHECKPOINT_ITER_FREQUENCY: -1  # set this variable to checkpoint every few iterations
