MODEL:
    # WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_ON: True
  RESNETS:
    DEPTH: 50
    NORM: "SyncBN"
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_fpn_backbone"
  META_ARCHITECTURE: "GeneralizedRCNN"
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    NORM: "SyncBN"
  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256], [512]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    # Detectron1 uses 2000 proposals per-batch,
    # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
    # which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "StandardROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  #################### sBN_precBN_lrpt1_warm50 ###########################
  BASE_LR: 0.1
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  WARMUP_ITERS: 50
  # ################### sBN_precBN_lrpt1_warm50_slpt3 #######################
  # BASE_LR: 0.1
  # STEPS: (60000, 80000)
  # MAX_ITER: 90000
  # WARMUP_ITERS: 50
  # WARMUP_FACTOR: 0.333
  # #################### sBN_precBN_lrpt02_warm100 ########################
  # BASE_LR: 0.02
  # STEPS: (60000, 80000)
  # MAX_ITER: 90000
  # WARMUP_ITERS: 100
  # #################### sBN_precBN_lrpt02_warm1000 #######################
  # BASE_LR: 0.02
  # STEPS: (60000, 80000)
  # MAX_ITER: 90000
  # WARMUP_ITERS: 1000
  # #################### sBN_precBN_lrpt02_warm100_2x #####################
  # BASE_LR: 0.02
  # STEPS: (120000, 160000)
  # MAX_ITER: 180000
  # WARMUP_ITERS: 100
  # #################### sBN_precBN_lrpt1_warm1000 ########################
  # BASE_LR: 0.1
  # STEPS: (60000, 80000)
  # MAX_ITER: 90000
  # WARMUP_ITERS: 1000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  FORMAT: "RGB" # torchvision models take RGB input
TEST:
  PRECISE_BN:
    ENABLED: True
VERSION: 2
