# @package _global_
config:
  MODEL:
    TRUNK:
      NAME: regnet
      TRUNK_PARAMS:
        REGNET:
          name: regnet_y_32gf
    HEAD:
      PARAMS: [
        ["swav_head", {"dims": [3712, 3712, 256], "use_bn": False, "num_clusters": []}],
      ]
