# @package _global_
config:
  MODEL:
    TRUNK:
      NAME: regnet
      TRUNK_PARAMS:
        REGNET:
          name: regnet_y_8gf
    HEAD:
      PARAMS: [
        ["swav_head", {"dims": [2016, 2016, 256], "use_bn": False, "num_clusters": []}],
      ]
