# @package _global_
config:
  MODEL:
    TRUNK:
      NAME: resnet
      TRUNK_PARAMS:
        RESNETS:
          DEPTH: 50
          WIDTH_MULTIPLIER: 3
    HEAD:
      PARAMS: [
        ['swav_head', {'dims': [6144, 6144, 128], 'use_bn': True, 'num_clusters': []}]
      ]
