# @package _global_
config:
  DATA:
    TRAIN:
      BATCHSIZE_PER_REPLICA: 16
    TEST:
      BATCHSIZE_PER_REPLICA: 16
  MODEL:
    TRUNK:
      NAME: regnet
      TRUNK_PARAMS:
        REGNET:
          depth: 20
          w_0: 352
          w_a: 147.48
          w_m: 2.4
          group_width: 328
    HEAD:
      PARAMS: [['mlp', {'dims': [4920, 1000]}]]
    SYNC_BN_CONFIG:
      CONVERT_BN_TO_SYNC_BN: True
      SYNC_BN_TYPE: apex
      GROUP_SIZE: 16
  DISTRIBUTED:
    NUM_NODES: 2  # we can't fit the model on 16GB machine so instead use 2 nodes
    INIT_METHOD: tcp
