_BASE_: "rn50_transfer_voc0712_detectron2_e2e.yaml"
MODEL:
  RESNETS:
    DEPTH: 50
    NORM: "SyncBN"
    STRIDE_IN_1X1: False
    ######## for rn50-w2 ###########
    WIDTH_PER_GROUP: 128
    RES2_OUT_CHANNELS: 512
    STEM_OUT_CHANNELS: 128
